apiVersion: v1
kind: Service
metadata:
  name: executor
  labels:
    app.kubernetes.io/name: executor
    app.kubernetes.io/component: application
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: executor
    app.kubernetes.io/component: application
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
